### ISSUE TITLE
program not starting..

### ISSUE THREAD

**Issue by jcallstrom** [bgraham11/honeywell-js#1]
Hello 
I've attempted to start up the program, but npm is looking for ./bin/www, which doesn't exist:

> user:honeywell-js user$ npm start
> 
> > home-automation@0.0.0 start /Users/user/GIT/honeywell-js
> > node ./
> 
> module.js:550
>     throw err;
>     ^
> 
> Error: Cannot find module '/Users/user/GIT/honeywell-js'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>     at bootstrap_node.js:625:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! home-automation@0.0.0 start: `node ./`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the home-automation@0.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

**Comment by jcallstrom** [comment]
Added the line "app.listen(3000)" to the app.js to launch the service and loaded the app.js manually, ie node app.js. May checkout to make the code change. :)

**Comment by mallemang** [comment]
jcallstrom:   I did as you suggested.   Now I get error:
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at E:\honeywell-js-master\honeywell-js-master\routes\auth.js:31:24
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)

**Comment by mallemang** [comment]
oh, i figured it out...my curl command wasn't working cause I'm working in windows.
BTW, I got it working using GLITCH.com environment...thank-you so very much bgraham11  :-)
